[project]
name = 'stacks-music-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.non-fungible-token]
path = 'contracts/non-fungible-token.clar'
clarity_version = 2
epoch = 2.4
depends_on = ["nft-trait"]

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
